### ISSUE TITLE
The field has disappeared 

### ISSUE THREAD

**Issue by slusarsu** [creagia/filament-code-field#15]
![Screenshot from 2023-05-30 19-21-58](https://github.com/creagia/filament-code-field/assets/20295847/36e3d2d6-394c-44b3-b365-69b21f8c9147)

Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Proxy.buildExtensionsArray (code-field.js:63:43)
    at Proxy.init (code-field.js:34:38)
    at module.esm.js:459:23
    at oe (module.esm.js:414:12)
    at le (module.esm.js:439:3)
    at module.esm.js:2131:27
    at Function.<anonymous> (module.esm.js:1196:55)
    at n (module.esm.js:577:7)
    at module.esm.js:582:5
    at Ge (module.esm.js:779:3)

**Comment by ricardcreagia** [comment]
Hi @slusarsu 

Sorry for the delay here. This issue should be fixed in the latest `1.0.10` version of the plugin.

Could you update the package and let us know if the issue has been resolved? Thanks!
